# Generated by Django 4.1.2 on 2022-10-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieCatalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='genero',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='genero',
            field=models.ManyToManyField(null=True, to='movieCatalog.generos'),
        ),
    ]
