# Generated by Django 4.1.2 on 2022-10-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieCatalog', '0002_remove_peliculas_genero_peliculas_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
